  Source.cpp
d:\projects\study\6semesterst\mathmod\project1\project1\source.cpp(32): warning C4286: 'std::runtime_error &': is caught by base class ('std::exception &') on line 27
  Project1.vcxproj -> D:\Projects\study\6semesterST\MathMod\Project1\Debug\Project1.exe
